# Test harmonypy
"""
Run just the small test (good for Github actions):

    uv run pytest

The small test data is available on Github.

Or run all of the tests (good for local development):

    uv run tests/test_harmony.py

The medium and large data will be downloaded automatically.
"""
from time import time

import csv
import gzip
import numpy as np
import os
import pytest
import sys
import harmonypy as hm
from harmonypy._harmony_cpp import _assignment_probabilities, _objective_converged


def pearsonr(x, y):
    """Pearson correlation coefficient (no scipy dependency)."""
    xm = x - x.mean()
    ym = y - y.mean()
    r = np.dot(xm, ym) / (np.linalg.norm(xm) * np.linalg.norm(ym))
    return r


def read_tsv(path):
    """Read a TSV file, return (header, columns_dict).

    Numeric columns are returned as float64 arrays.
    Non-numeric columns are returned as string arrays.
    """
    with gzip.open(path, "rt") if path.endswith(".gz") else open(path) as f:
        reader = csv.reader(f, delimiter="\t")
        header = next(reader)
        rows = list(reader)
    cols = {}
    for i, name in enumerate(header):
        values = [row[i] for row in rows]
        try:
            cols[name] = np.array(values, dtype=np.float64)
        except ValueError:
            cols[name] = np.array(values)
    return header, cols


def cols_to_matrix(cols, header):
    """Extract numeric columns into a matrix (N x d).

    An unnamed column holds row names, such as the row index that pandas
    writes, so it is skipped.
    """
    numeric = []
    for name in header:
        if name and cols[name].dtype == np.float64:
            numeric.append(cols[name])
    return np.column_stack(numeric)


def _get_current_rss_mb():
    """Get current RSS (resident set size) in MB. Works on macOS and Linux.

    Unlike resource.getrusage(RUSAGE_SELF).ru_maxrss which only reports the
    lifetime high-water mark, this returns the *current* RSS — so before/after
    deltas correctly capture memory that was allocated and freed by C++ code.
    """
    if sys.platform == "darwin":
        import ctypes, ctypes.util
        libc = ctypes.CDLL(ctypes.util.find_library("c"))

        MACH_TASK_BASIC_INFO = 20
        class mach_task_basic_info(ctypes.Structure):
            _fields_ = [
                ("virtual_size", ctypes.c_uint64),
                ("resident_size", ctypes.c_uint64),
                ("resident_size_max", ctypes.c_uint64),
                ("user_time_seconds", ctypes.c_uint32),
                ("user_time_microseconds", ctypes.c_uint32),
                ("system_time_seconds", ctypes.c_uint32),
                ("system_time_microseconds", ctypes.c_uint32),
                ("policy", ctypes.c_int32),
                ("suspend_count", ctypes.c_int32),
            ]

        info = mach_task_basic_info()
        count = ctypes.c_uint32(ctypes.sizeof(info) // 4)
        libc.task_info(
            libc.mach_task_self(),
            MACH_TASK_BASIC_INFO,
            ctypes.byref(info),
            ctypes.byref(count),
        )
        return info.resident_size / 1024 / 1024
    else:
        # Linux: read from /proc/self/status
        with open("/proc/self/status") as f:
            for line in f:
                if line.startswith("VmRSS:"):
                    return int(line.split()[1]) / 1024  # kB -> MB
        return 0.0


def test_run_harmony_small():
    # The reference is generated by scripts/generate_harmony2_reference.R with
    # R harmony from the harmony2 branch, which this C++ port follows
    # step-by-step. Per-PC correlation is >= 0.998 on both macOS and
    # Linux, so 0.99 leaves margin for compiler and float32 differences
    # while still catching real algorithmic drift.
    run_harmony(
        meta_tsv="data/pbmc_3500_meta.tsv.gz",
        pcs_tsv="data/pbmc_3500_pcs.tsv.gz",
        harmonized_tsv="data/pbmc_3500_pcs_harmony2.tsv.gz",
        batch_var="donor",
        min_correlation=0.99,
    )


def test_run_harmony_with_lab_and_day():
    """Correcting for lab and day should return finite coordinates for every cell."""
    n_cells = 120
    n_coordinates = 5
    random_seed = 0
    lab_labels = ["lab_a", "lab_b"]
    day_labels = ["Monday", "Tuesday", "Wednesday"]

    # A small, repeatable example: each cell has coordinates, a lab and a day.
    rng = np.random.default_rng(random_seed)
    cell_coordinates = rng.normal(size=(n_cells, n_coordinates))
    cell_metadata = {
        "lab": rng.permutation(np.tile(lab_labels, n_cells // len(lab_labels))),
        "day": rng.permutation(np.tile(day_labels, n_cells // len(day_labels))),
    }

    # This test must run against an ASan build to detect the memory error
    # that motivated it.
    # Limit iterations and use one thread to keep this test quick and repeatable.
    result = hm.run_harmony(
        cell_coordinates, cell_metadata, ["lab", "day"],
        max_iter_harmony=2,
        max_iter_kmeans=2,
        random_state=random_seed,
        ncores=1,
        verbose=False,
    )

    corrected_coordinates = result.Z_corr
    assert corrected_coordinates.shape == cell_coordinates.shape
    assert np.isfinite(corrected_coordinates).all()


def test_ridge_does_not_reverse_two_cells():
    values = np.array([[1.0], [2.0]])
    metadata = {"lab": ["A", "B"], "day": ["Monday", "Tuesday"]}
    result = hm.run_harmony(
        values, metadata, ["lab", "day"],
        nclust=1, max_iter_harmony=1, max_iter_kmeans=0,
        lamb=0.5, sigma=np.ones(1), ncores=1, verbose=False,
    )

    # With equal weights and penalties, these values should move closer
    # without reversing their order.
    assert result.Z_corr[0, 0] < result.Z_corr[1, 0]


def test_at_limit_leaves_coordinates_unchanged():
    coordinates = np.array([[1.0], [2.0], [3.0], [4.0]])
    metadata = {
        "lab": ["a", "a", "b", "b"],
        "day": ["a", "b", "a", "b"],
    }
    n_clusters = 2
    limit = 1 / n_clusters
    result = hm.run_harmony(
        coordinates, metadata, ["lab", "day"], nclust=n_clusters,
        max_iter_harmony=1, max_iter_kmeans=1, theta=0, lamb=1,
        batch_prop_cutoff=limit, ncores=1, verbose=False,
    )

    # No lab or day is above the limit, so the coordinates stay unchanged.
    np.testing.assert_array_equal(result.R, np.full((len(coordinates), n_clusters), limit))
    np.testing.assert_array_equal(result.Z_corr, coordinates)


def direct_ridge_correction(coordinates, labels, assignments, alpha=0.2, cutoff=1e-5, lamb=None):
    """One ridge correction step, solved directly in float64 with an explicit inverse.

    For each cluster, regress the coordinates on an intercept and one indicator
    per kept group, weighting cells by their assignment to the cluster. Only
    cells in at least one kept group count toward the intercept. Each group's
    penalty is alpha times its expected weight in the cluster, or lamb if given.
    """
    indicators = []
    for values in labels:
        _, codes = np.unique(values, return_inverse=True)
        indicators.append(np.eye(codes.max() + 1)[codes])
    design = np.hstack(indicators)
    covariate = np.repeat(np.arange(len(indicators)), [g.shape[1] for g in indicators])
    sizes = design.sum(0)
    share_of_cells = (sizes / len(coordinates)).astype(np.float32)
    original = coordinates.astype(np.float32).astype(np.float64)
    corrected = original.copy()
    for weights in assignments.T.astype(np.float64):
        fraction = (design.T @ weights) / sizes
        above = fraction > cutoff
        levels = np.bincount(covariate[above], minlength=len(indicators))
        keep = above & (levels[covariate] > 1)
        if not keep.any():
            continue
        X = np.column_stack([design[:, keep].any(axis=1), design[:, keep]])
        if lamb is None:
            group_penalty = alpha * weights.sum() * share_of_cells[keep]
        else:
            group_penalty = np.full(keep.sum(), float(np.float32(lamb)))
        penalty = np.concatenate([[0.0], group_penalty])
        weighted = X.T * weights
        coef = np.linalg.inv(weighted @ X + np.diag(penalty)) @ (weighted @ original)
        corrected -= (design[:, keep] * weights[:, None]) @ coef[1:]
    return corrected


@pytest.mark.parametrize("lamb", [None, 1e-3])
@pytest.mark.parametrize(
    "variables",
    [["lab"], ["lab", "day"], ["day", "lab"], ["lab", "day", "kit"], ["kit", "day", "lab"]],
)
def test_ridge_correction_matches_direct_solution(variables, lamb):
    """One correction step agrees with solving the ridge regression directly.

    With a small lamb the system is nearly singular, because the intercept is
    the sum of each variable's groups, so the result depends on every digit of
    the sums it is built from. The variable with the most groups is listed
    first or last, which changes how the system is split for the solve.
    """
    rng = np.random.default_rng(1)
    n_cells = 2000
    metadata = {
        "lab": rng.choice(["a", "b", "c", "d"], n_cells),
        "day": rng.choice(["Monday", "Tuesday", "Wednesday"], n_cells),
        "kit": rng.choice(["v1", "v2"], n_cells),
    }
    coordinates = rng.normal(size=(n_cells, 4))
    coordinates[metadata["lab"] == "a"] += 1.5
    coordinates[metadata["day"] == "Monday"] -= 1.0

    result = hm.run_harmony(
        coordinates, metadata, variables, nclust=5, lamb=lamb,
        max_iter_harmony=1, max_iter_kmeans=0, verbose=False,
    )

    expected = direct_ridge_correction(coordinates, [metadata[v] for v in variables], result.R, lamb=lamb)
    np.testing.assert_allclose(result.Z_corr, expected, rtol=1e-4, atol=1e-4)


@pytest.mark.parametrize("variables", [["lab", "day"], ["day", "lab", "kit"]])
def test_ridge_correction_matches_direct_solution_when_groups_are_dropped(variables):
    """Clusters that keep only some groups (batch_prop_cutoff) solve smaller systems."""
    rng = np.random.default_rng(5)
    n_cells = 3000
    labs = np.array(["a", "b", "c", "d", "e"])
    lab = rng.choice(labs, n_cells, p=[0.4, 0.3, 0.15, 0.1, 0.05])
    metadata = {
        "lab": lab,
        "day": rng.choice(["Monday", "Tuesday", "Wednesday"], n_cells),
        "kit": rng.choice(["v1", "v2"], n_cells),
    }
    coordinates = rng.normal(size=(n_cells, 4))
    # Each lab sits in its own region, so most clusters hold few labs.
    coordinates[:, 0] += 3.0 * np.searchsorted(labs, lab)
    cutoff = 0.1

    result = hm.run_harmony(
        coordinates, metadata, variables, nclust=8, batch_prop_cutoff=cutoff,
        max_iter_harmony=1, max_iter_kmeans=0, ncores=4, verbose=False,
    )

    expected = direct_ridge_correction(coordinates, [metadata[v] for v in variables], result.R, cutoff=cutoff)
    np.testing.assert_allclose(result.Z_corr, expected, rtol=1e-4, atol=1e-4)
    # Some clusters drop a lab, and some still correct for several labs.
    codes = np.searchsorted(labs, lab)
    fraction = np.stack([np.bincount(codes, weights=r) for r in result.R.T]) / np.bincount(codes)
    kept = fraction > cutoff
    assert (~kept).any() and (kept.sum(axis=1) > 1).any()


def test_small_lamb_with_large_clusters():
    """A small positive lamb is solved, not reported as singular.

    With one variable the solve's pivot is about lamb times the number of
    groups, here 2e-3, while each cluster weighs about 30,000 cells.
    """
    rng = np.random.default_rng(7)
    n_cells = 60000
    metadata = {"lab": rng.choice(["a", "b"], n_cells)}
    coordinates = rng.normal(size=(n_cells, 4))
    coordinates[metadata["lab"] == "a"] += 1.0

    result = hm.run_harmony(
        coordinates, metadata, "lab", nclust=2, lamb=1e-3,
        max_iter_harmony=1, max_iter_kmeans=0, verbose=False,
    )

    expected = direct_ridge_correction(coordinates, [metadata["lab"]], result.R, lamb=1e-3)
    np.testing.assert_allclose(result.Z_corr, expected, rtol=1e-4, atol=1e-4)


@pytest.mark.parametrize("variables", [["lab"], ["lab", "day"]])
@pytest.mark.parametrize("n_cells, n_dims", [(600, 4), (3000, 20)])
def test_zero_lamb_raises(variables, n_cells, n_dims):
    """Without a penalty the ridge system is singular, which is reported.

    With 3000 cells and two variables the clusters are solved on the thread
    pool, so the error is raised on a worker thread.
    """
    rng = np.random.default_rng(4)
    metadata = {
        "lab": rng.choice(["a", "b", "c"], n_cells),
        "day": rng.choice(["Monday", "Tuesday"], n_cells),
    }
    coordinates = rng.normal(size=(n_cells, n_dims))

    with pytest.raises(RuntimeError, match="singular"):
        hm.run_harmony(coordinates, metadata, variables, lamb=0, ncores=4, verbose=False)


@pytest.mark.parametrize("penalty", [{"lamb": -0.5}, {"lamb": np.nan}, {"alpha": -0.2}])
def test_negative_penalty_raises(penalty):
    """A negative or non-finite lamb or alpha is rejected before running."""
    rng = np.random.default_rng(8)
    coordinates = rng.normal(size=(300, 4))
    metadata = {"lab": rng.choice(["a", "b"], 300)}

    with pytest.raises(ValueError, match="not negative"):
        hm.run_harmony(coordinates, metadata, "lab", nclust=5, verbose=False, **penalty)


@pytest.mark.parametrize("variables", [["lab", "day"], ["lab", "day", "kit"]])
def test_results_do_not_depend_on_ncores(variables):
    """Work is divided the same way for any number of threads.

    The data are large enough (3000 cells, 20 dimensions, 100 clusters) that
    the per-cluster ridge solves also run on the thread pool.
    """
    rng = np.random.default_rng(2)
    n_cells = 3000
    metadata = {
        "lab": rng.choice(["a", "b", "c"], n_cells),
        "day": rng.choice(["Monday", "Tuesday"], n_cells),
        "kit": rng.choice(["v1", "v2"], n_cells),
    }
    coordinates = rng.normal(size=(n_cells, 20))
    coordinates[metadata["lab"] == "a"] += 1.0

    results = [
        hm.run_harmony(coordinates, metadata, variables, ncores=ncores, verbose=False)
        for ncores in (1, 3)
    ]

    np.testing.assert_array_equal(results[0].Z_corr, results[1].Z_corr)
    np.testing.assert_array_equal(results[0].R, results[1].R)
    assert results[0].objective_harmony == results[1].objective_harmony


def test_more_threads_than_cpus():
    """A larger ncores than there are CPUs is capped instead of failing."""
    rng = np.random.default_rng(3)
    coordinates = rng.normal(size=(300, 5))
    metadata = {"lab": rng.choice(["a", "b"], 300)}

    result = hm.run_harmony(coordinates, metadata, "lab", nclust=5, ncores=2**40, verbose=False)

    assert np.isfinite(result.Z_corr).all()


def test_z_cos_is_unit_length_z_corr():
    """Z_cos is the corrected embedding with each cell scaled to unit length."""
    rng = np.random.default_rng(6)
    coordinates = rng.normal(size=(300, 5)) * 10
    metadata = {"lab": rng.choice(["a", "b"], 300)}

    result = hm.run_harmony(coordinates, metadata, "lab", nclust=5, verbose=False)

    lengths = np.linalg.norm(result.Z_cos, axis=1)
    np.testing.assert_allclose(lengths, 1.0, rtol=1e-6)
    np.testing.assert_allclose(
        result.Z_cos, result.Z_corr / np.linalg.norm(result.Z_corr, axis=1, keepdims=True),
        rtol=1e-6, atol=1e-7,
    )


def test_read_only_input():
    """Arrays that cannot be written to, such as memory-mapped files, are accepted."""
    rng = np.random.default_rng(3)
    coordinates = rng.normal(size=(300, 5))
    coordinates.flags.writeable = False
    metadata = {"lab": rng.choice(["a", "b"], 300)}

    result = hm.run_harmony(coordinates, metadata, "lab", nclust=5, verbose=False)

    assert np.isfinite(result.Z_corr).all()


def test_nonfinite_input_raises():
    """Missing coordinates raise an error instead of hanging the k-means start."""
    coordinates = np.random.default_rng(4).normal(size=(300, 5))
    coordinates[::2, 0] = np.nan
    metadata = {"lab": np.repeat(["a", "b"], 150)}

    with pytest.raises(ValueError, match="NaN"):
        hm.run_harmony(coordinates, metadata, "lab", nclust=10, verbose=False)


def test_sigma_must_match_nclust():
    rng = np.random.default_rng(5)
    coordinates = rng.normal(size=(300, 5))
    metadata = {"lab": rng.choice(["a", "b"], 300)}

    with pytest.raises(ValueError, match="sigma"):
        hm.run_harmony(coordinates, metadata, "lab", nclust=10, sigma=np.full(5, 0.1), verbose=False)


def optimizer_case():
    data_mat = np.array(
        [[1.0, 0.0], [0.8, 0.2], [0.0, 1.0],
         [-1.0, 0.0], [-0.8, -0.2], [0.0, -1.0]]
    )
    meta_data = {"batch": np.array(["a", "a", "b", "b", "a", "b"])}
    return data_mat, meta_data


@pytest.mark.parametrize(
    ("obj_old", "obj_new", "epsilon", "expected"),
    [
        (100.0, 101.0, 0.01, False),
        (100.0, 99.5, 0.01, True),
        (100.0, 90.0, 0.01, False),
        (100.0, 99.0, 0.01, False),
        (-100.0, -100.5, 0.01, True),
        (-100.0, -99.0, 0.01, False),
        (0.0, 0.0, 0.01, True),
        (0.0, 1.0, 0.01, False),
        (0.0, -1.0, 0.01, False),
        (np.nan, 1.0, 0.01, False),
        (1.0, np.nan, 0.01, False),
        (np.inf, 1.0, 0.01, False),
        (1.0, np.inf, 0.01, False),
        (-np.inf, 1.0, 0.01, False),
        (1.0, -np.inf, 0.01, False),
        (1.0, 1.0, np.nan, False),
    ],
)
def test_objective_convergence(obj_old, obj_new, epsilon, expected):
    assert _objective_converged(obj_old, obj_new, epsilon) is expected


def test_objective_increase_does_not_stop_harmony():
    data_mat, meta_data = optimizer_case()

    ho = hm.run_harmony(
        data_mat,
        meta_data,
        "batch",
        sigma=1.0,
        theta=2.0,
        nclust=2,
        lamb=1.0,
        block_size=0.5,
        max_iter_harmony=2,
        max_iter_kmeans=1,
        epsilon_cluster=0.0,
        epsilon_harmony=0.01,
        verbose=False,
        random_state=0,
        ncores=1,
    )

    assert ho.objective_harmony[1] > ho.objective_harmony[0]
    assert len(ho.objective_harmony) == 3


def assignment_inputs():
    distances = np.array(
        [[0.2, 1.1, 0.7], [1.2, 0.3, 0.6], [0.8, 0.9, 0.2]]
    )
    sigma = np.array([0.8, 1.2, 0.6])
    E = np.array(
        [[2.0, 4.0, 1.0, 3.0],
         [3.0, 2.0, 4.0, 1.0],
         [1.0, 3.0, 2.0, 4.0]]
    )
    O = np.array(
        [[3.0, 1.0, 2.0, 4.0],
         [1.0, 4.0, 3.0, 2.0],
         [2.0, 3.0, 1.0, 4.0]]
    )
    theta = np.array([2.0, 1.5, 0.5, 3.0])
    batch_ids = np.array([[0, 1, 0], [2, 3, 3]], dtype=np.int64)
    return distances, sigma, E, O, theta, batch_ids


def old_assignment_probabilities(distances, sigma, E, O, theta, batch_ids):
    probabilities = np.exp(-distances / sigma[:, None])
    probabilities /= probabilities.sum(axis=0)
    ratio = (2 * E + 1) / (O + E + 1)
    for cell_batches in batch_ids:
        probabilities *= ratio[:, cell_batches] ** theta[cell_batches]
    probabilities /= probabilities.sum(axis=0)
    return probabilities


def test_log_assignments_match_moderate_multiplicative_weights():
    inputs = tuple(np.ascontiguousarray(value) for value in assignment_inputs())

    actual = _assignment_probabilities(*inputs)
    expected = old_assignment_probabilities(*inputs)

    np.testing.assert_allclose(actual, expected, rtol=2e-6, atol=1e-7)


def test_log_assignments_ignore_cell_logit_shifts():
    distances, sigma, E, O, theta, batch_ids = assignment_inputs()
    inputs = tuple(
        np.ascontiguousarray(value)
        for value in (distances, sigma, E, O, theta, batch_ids)
    )
    expected = _assignment_probabilities(*inputs)
    offsets = np.array([30.0, -40.0, 20.0])
    shifted_distances = distances - sigma[:, None] * offsets

    actual = _assignment_probabilities(
        np.ascontiguousarray(shifted_distances), *inputs[1:]
    )

    np.testing.assert_allclose(actual, expected, rtol=2e-5, atol=1e-6)


def test_log_assignments_preserve_covariate_penalties():
    distances, sigma, E, O, theta, batch_ids = assignment_inputs()
    neutral_theta = theta.copy()
    neutral_theta[2:] = 0.0

    one_covariate = _assignment_probabilities(
        *tuple(
            np.ascontiguousarray(value)
            for value in (distances, sigma, E, O, neutral_theta, batch_ids[:1])
        )
    )
    neutral_covariate = _assignment_probabilities(
        *tuple(
            np.ascontiguousarray(value)
            for value in (distances, sigma, E, O, neutral_theta, batch_ids)
        )
    )
    reversed_covariates = _assignment_probabilities(
        *tuple(
            np.ascontiguousarray(value)
            for value in (distances, sigma, E, O, theta, batch_ids[::-1])
        )
    )
    original = _assignment_probabilities(
        *tuple(
            np.ascontiguousarray(value)
            for value in (distances, sigma, E, O, theta, batch_ids)
        )
    )

    np.testing.assert_allclose(neutral_covariate, one_covariate, atol=1e-7)
    np.testing.assert_allclose(reversed_covariates, original, atol=1e-7)


def test_extreme_theta_and_unbalanced_batches_remain_finite():
    distances = np.array(
        [[0.1, 0.3, 0.5, 0.7, 0.9, 1.1],
         [1.1, 0.9, 0.7, 0.5, 0.3, 0.1]]
    )
    sigma = np.array([0.1, 0.1])
    E = np.array([[5.0, 1.0], [5.0, 1.0]])
    O = np.array([[5.0, 0.0], [0.0, 1.0]])
    theta = np.array([1000.0, 1000.0])
    batch_ids = np.array([[0, 0, 0, 0, 0, 1]], dtype=np.int64)

    probabilities = _assignment_probabilities(
        *tuple(
            np.ascontiguousarray(value)
            for value in (distances, sigma, E, O, theta, batch_ids)
        )
    )

    assert np.isfinite(probabilities).all()
    assert (probabilities >= 0).all()
    np.testing.assert_allclose(probabilities.sum(axis=0), 1.0, atol=1e-7)

    data_mat, _ = optimizer_case()
    meta_data = {"batch": np.array(["a", "a", "a", "a", "a", "b"])}
    ho = hm.run_harmony(
        data_mat,
        meta_data,
        "batch",
        sigma=1e-4,
        theta=1000.0,
        nclust=2,
        lamb=1.0,
        block_size=0.5,
        max_iter_harmony=1,
        max_iter_kmeans=1,
        verbose=False,
        random_state=0,
        ncores=1,
    )

    assert np.isfinite(ho.R).all()
    assert np.isfinite(ho.objective_harmony).all()
    assert np.isfinite(ho.Z_corr).all()
    np.testing.assert_allclose(ho.R.sum(axis=1), 1.0, atol=1e-7)


def test_small_sigma_assignments_remain_finite():
    data_mat, meta_data = optimizer_case()

    ho = hm.run_harmony(
        data_mat,
        meta_data,
        "batch",
        sigma=1e-4,
        nclust=2,
        lamb=1.0,
        block_size=0.5,
        max_iter_harmony=1,
        max_iter_kmeans=1,
        verbose=False,
        random_state=0,
        ncores=1,
    )

    assert np.isfinite(ho.R).all()
    assert np.isfinite(ho.objective_harmony).all()
    assert np.isfinite(ho.Z_corr).all()
    assert (ho.R >= 0).all()
    np.testing.assert_allclose(ho.R.sum(axis=1), 1.0, atol=1e-7)


def test_nonfinite_assignments_raise_numerical_error():
    data_mat, meta_data = optimizer_case()

    with pytest.raises(RuntimeError) as error:
        hm.run_harmony(
            data_mat,
            meta_data,
            "batch",
            sigma=float("nan"),
            nclust=2,
            lamb=1.0,
            max_iter_harmony=1,
            max_iter_kmeans=1,
            verbose=False,
            random_state=0,
            ncores=1,
        )

    message = str(error.value)
    assert "assignment normalizers must be finite and positive" in message
    assert "sigma=[nan, nan]" in message
    assert "theta=[2, 2]" in message
    assert "block_size=0.05" in message


def test_random_seed():
    print("\n" + "=" * 60)
    print("TEST: test_random_seed")
    print("=" * 60)

    _, meta_cols = read_tsv("data/pbmc_3500_meta.tsv.gz")
    _, pcs_cols = read_tsv("data/pbmc_3500_pcs.tsv.gz")
    data_mat = cols_to_matrix(pcs_cols, list(pcs_cols.keys()))

    def run(random_state):
        ho = hm.run_harmony(data_mat,
                            meta_cols, ['donor'],
                            max_iter_harmony=2,
                            max_iter_kmeans=2,
                            verbose=False,
                            random_state=random_state)
        return ho.Z_corr

    # Assert same results when random_state is set.
    print("\n--- Testing reproducibility with random_state=42 ---")
    result1 = run(42)
    result2 = run(42)
    diff_same_seed = np.abs(result1 - result2).sum()
    print(f"Difference between two runs with same seed: {diff_same_seed:.6f}")
    np.testing.assert_allclose(result1, result2, rtol=1e-3, atol=1e-4)
    print("PASSED: Same seed produces similar results")

    # Assert different values when random_state is different
    print("\n--- Testing variability with different seeds ---")
    result3 = run(123)
    result4 = run(456)
    diff_diff_seed = np.abs(result3 - result4).sum()
    print(f"Difference between runs with different seeds: {diff_diff_seed:.2f}")
    assert diff_diff_seed > 1000, f"Expected diff > 1000, got {diff_diff_seed}"
    print("PASSED: Different seeds produce different results")


def run_harmony(meta_tsv, pcs_tsv, harmonized_tsv, batch_var, min_correlation=0.9):
    print("\n" + "=" * 60)
    print("TEST: test_run_harmony")
    print("=" * 60)

    if not os.path.exists(meta_tsv):
        return {"time": 0, "rss_delta_mb": 0}

    # Load input data
    meta_header, meta_cols = read_tsv(meta_tsv)
    pcs_header, pcs_cols = read_tsv(pcs_tsv)
    data_mat = cols_to_matrix(pcs_cols, pcs_header)

    N = len(meta_cols[batch_var])
    unique_batches = np.unique(meta_cols[batch_var])
    print("\n--- Input Data ---")
    print(f"data_mat shape: {data_mat.shape} (cells x PCs)")
    print(f"meta_data columns: {meta_header}")
    print(f"Batch variable '{batch_var}' unique values: {unique_batches}")

    print("\n--- Running Harmony ---")
    import gc
    gc.collect()
    rss_before = _get_current_rss_mb()
    start = time()
    ho = hm.run_harmony(data_mat, meta_cols, [batch_var])
    end = time()
    rss_after = _get_current_rss_mb()
    rss_delta_mb = rss_after - rss_before
    print(f"\nHarmony completed in {end - start:.2f} seconds")
    print(f"  RSS before: {rss_before:.1f} MB")
    print(f"  RSS after:  {rss_after:.1f} MB")
    print(f"  RSS delta:  {rss_delta_mb:.1f} MB")

    print("\n--- Harmony Object Info ---")
    print(f"Number of clusters (K): {ho.K}")
    print(f"Number of harmony iterations: {len(ho.objective_harmony)}")
    print(f"K-means rounds per iteration: {ho.kmeans_rounds}")
    print(f"Z_corr shape: {ho.Z_corr.shape} (cells x PCs)")
    print(f"Z_orig shape: {ho.Z_orig.shape}")

    # Check convergence
    print("\n--- Convergence ---")
    print(f"Objective (harmony) history: {[f'{x:.2f}' for x in ho.objective_harmony]}")

    # Compare to expected results from R
    res = ho.Z_corr  # cells x PCs
    harm_header, harm_cols = read_tsv(harmonized_tsv)
    harm = cols_to_matrix(harm_cols, harm_header)
    print("\n--- Comparison with R Results ---")
    print(f"Expected result shape: {harm.shape}")

    n_pcs = min(res.shape[1], harm.shape[1])
    cors_values = []
    for i in range(n_pcs):
        cors_values.append(pearsonr(res[:, i], harm[:, i]))
    print(f"Correlations (Python vs R) per PC: {[f'{x:.3f}' for x in cors_values]}")
    print(f"Min correlation: {min(cors_values):.3f}")
    print(f"Mean correlation: {np.mean(cors_values):.3f}")

    # Correlation between test PCs and observed PCs is high
    assert np.all(np.array(cors_values) >= min_correlation), \
        f"Some correlations < {min_correlation}: {cors_values}"
    print(f"PASSED: All correlations >= {min_correlation}")

    return {"time": end - start, "rss_delta_mb": rss_delta_mb}


def download_data():
    if not os.path.exists("data"):
        os.makedirs("data")
    remote_url = "https://immunogenomics.io/downloads"
    files = [
        "acute_myeloid_obs.tsv.gz",
        "acute_myeloid_pcs.tsv.gz",
        "acute_myeloid_pcs_harmonized.tsv.gz",
    ]
    for file in files:
        if not os.path.exists(f"data/{file}"):
            import wget
            print(f"Downloading {file}")
            wget.download(f"{remote_url}/{file}", f"data/{file}")


if __name__ == "__main__":
    print("\n" + "#" * 60)
    print("# Running harmonypy tests")
    print("#" * 60)
    print()

    timings = {}

    download_data()

    timings['small'] = run_harmony(
        meta_tsv="data/pbmc_3500_meta.tsv.gz",
        pcs_tsv="data/pbmc_3500_pcs.tsv.gz",
        harmonized_tsv="data/pbmc_3500_pcs_harmony2.tsv.gz",
        batch_var="donor",
        min_correlation=0.99,
    )

    timings['medium'] = run_harmony(
        meta_tsv="data/ircolitis_blood_cd8_obs.tsv.gz",
        pcs_tsv="data/ircolitis_blood_cd8_pcs.tsv.gz",
        harmonized_tsv="data/ircolitis_blood_cd8_pcs_harmonized.tsv.gz",
        batch_var="batch"
    )

    timings['large'] = run_harmony(
        meta_tsv="data/acute_myeloid_obs.tsv.gz",
        pcs_tsv="data/acute_myeloid_pcs.tsv.gz",
        harmonized_tsv="data/acute_myeloid_pcs_harmonized.tsv.gz",
        batch_var="batch"
    )

    test_random_seed()

    print("\n" + "#" * 60)
    print("# Performance Summary")
    print("#" * 60)
    print(f"  {'Dataset':<22} {'Time':>8} {'RSS delta':>12}")
    print(f"  {'-'*22} {'-'*8} {'-'*12}")
    for label, key in [("Small (3.5k cells)", "small"),
                       ("Medium (69k cells)", "medium"),
                       ("Large (858k cells)", "large")]:
        t = timings[key]
        print(f"  {label:<22} {t['time']:>7.2f}s {t['rss_delta_mb']:>8.1f} MB")

    print("\n" + "#" * 60)
    print("# All tests passed!")
    print("#" * 60)
